### ISSUE TITLE
[bug] test failure on 32-bit arches

### ISSUE THREAD

**Issue by werdahias** [NoXF/libwebp-sys#22]
I upload the webp-sys crate to debian today. Some bindgen tests fail on 32-bit arches (arm, x86):

```
running 19 tests
test ffi::bindgen_test_layout_WebPAnimDecoderOptions ... ok
test ffi::bindgen_test_layout_WebPAnimEncoderOptions ... ok
test ffi::bindgen_test_layout_WebPAnimInfo ... ok
test ffi::bindgen_test_layout_WebPAuxStats ... ok
test ffi::bindgen_test_layout_WebPBitstreamFeatures ... ok
test ffi::bindgen_test_layout_WebPConfig ... ok
test ffi::bindgen_test_layout_WebPDecBuffer ... FAILED
test ffi::bindgen_test_layout_WebPChunkIterator ... FAILED
test ffi::bindgen_test_layout_WebPDecBuffer__bindgen_ty_1 ... FAILED
test ffi::bindgen_test_layout_WebPDecoderOptions ... ok
test ffi::bindgen_test_layout_WebPData ... FAILED
test ffi::bindgen_test_layout_WebPDecoderConfig ... FAILED
test ffi::bindgen_test_layout_WebPIterator ... FAILED
test ffi::bindgen_test_layout_WebPMemoryWriter ... FAILED
test ffi::bindgen_test_layout_WebPMuxAnimParams ... ok
test ffi::bindgen_test_layout_WebPMuxFrameInfo ... FAILED
test ffi::bindgen_test_layout_WebPYUVABuffer ... FAILED
test ffi::bindgen_test_layout_WebPRGBABuffer ... FAILED
test ffi::bindgen_test_layout_WebPPicture ... FAILED

failures:

---- ffi::bindgen_test_layout_WebPDecBuffer stdout ----
thread 'ffi::bindgen_test_layout_WebPDecBuffer' panicked at 'assertion failed: `(left == right)`
  left: `84`,
 right: `120`: Size of: WebPDecBuffer', src/ffi.rs:1710:5
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.67.1/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.67.1/library/core/src/panicking.rs:64:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /usr/src/rustc-1.67.1/library/core/src/panicking.rs:199:5
   4: libwebp_sys::ffi::bindgen_test_layout_WebPDecBuffer
             at /usr/share/cargo/registry/libwebp-sys-0.9.2/src/ffi.rs:1710:5
   5: libwebp_sys::ffi::bindgen_test_layout_WebPDecBuffer::{{closure}}
             at /usr/share/cargo/registry/libwebp-sys-0.9.2/src/ffi.rs:1707:40
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.67.1/library/core/src/ops/function.rs:507:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.67.1/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- ffi::bindgen_test_layout_WebPChunkIterator stdout ----
thread 'ffi::bindgen_test_layout_WebPChunkIterator' panicked at 'assertion failed: `(left == right)`
  left: `44`,
 right: `56`: Size of: WebPChunkIterator', src/ffi.rs:2978:5
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.67.1/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.67.1/library/core/src/panicking.rs:64:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /usr/src/rustc-1.67.1/library/core/src/panicking.rs:199:5
   4: libwebp_sys::ffi::bindgen_test_layout_WebPChunkIterator
             at /usr/share/cargo/registry/libwebp-sys-0.9.2/src/ffi.rs:2978:5
   5: libwebp_sys::ffi::bindgen_test_layout_WebPChunkIterator::{{closure}}
             at /usr/share/cargo/registry/libwebp-sys-0.9.2/src/ffi.rs:2975:44
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.67.1/library/core/src/ops/function.rs:507:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.67.1/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- ffi::bindgen_test_layout_WebPDecBuffer__bindgen_ty_1 stdout ----
thread 'ffi::bindgen_test_layout_WebPDecBuffer__bindgen_ty_1' panicked at 'assertion failed: `(left == right)`
  left: `48`,
 right: `80`: Size of: WebPDecBuffer__bindgen_ty_1', src/ffi.rs:1670:5
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.67.1/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.67.1/library/core/src/panicking.rs:64:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /usr/src/rustc-1.67.1/library/core/src/panicking.rs:199:5
   4: libwebp_sys::ffi::bindgen_test_layout_WebPDecBuffer__bindgen_ty_1
             at /usr/share/cargo/registry/libwebp-sys-0.9.2/src/ffi.rs:1670:5
   5: libwebp_sys::ffi::bindgen_test_layout_WebPDecBuffer__bindgen_ty_1::{{closure}}
             at /usr/share/cargo/registry/libwebp-sys-0.9.2/src/ffi.rs:1666:54
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.67.1/library/core/src/ops/function.rs:507:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.67.1/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- ffi::bindgen_test_layout_WebPData stdout ----
thread 'ffi::bindgen_test_layout_WebPData' panicked at 'assertion failed: `(left == right)`
  left: `8`,
 right: `16`: Size of: WebPData', src/ffi.rs:2291:5
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.67.1/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.67.1/library/core/src/panicking.rs:64:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /usr/src/rustc-1.67.1/library/core/src/panicking.rs:199:5
   4: libwebp_sys::ffi::bindgen_test_layout_WebPData
             at /usr/share/cargo/registry/libwebp-sys-0.9.2/src/ffi.rs:2291:5
   5: libwebp_sys::ffi::bindgen_test_layout_WebPData::{{closure}}
             at /usr/share/cargo/registry/libwebp-sys-0.9.2/src/ffi.rs:2288:35
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.67.1/library/core/src/ops/function.rs:507:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.67.1/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- ffi::bindgen_test_layout_WebPDecoderConfig stdout ----
thread 'ffi::bindgen_test_layout_WebPDecoderConfig' panicked at 'assertion failed: `(left == right)`
  left: `200`,
 right: `240`: Size of: WebPDecoderConfig', src/ffi.rs:2189:5
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.67.1/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.67.1/library/core/src/panicking.rs:64:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /usr/src/rustc-1.67.1/library/core/src/panicking.rs:199:5
   4: libwebp_sys::ffi::bindgen_test_layout_WebPDecoderConfig
             at /usr/share/cargo/registry/libwebp-sys-0.9.2/src/ffi.rs:2189:5
   5: libwebp_sys::ffi::bindgen_test_layout_WebPDecoderConfig::{{closure}}
             at /usr/share/cargo/registry/libwebp-sys-0.9.2/src/ffi.rs:2186:44
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.67.1/library/core/src/ops/function.rs:507:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.67.1/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- ffi::bindgen_test_layout_WebPIterator stdout ----
thread 'ffi::bindgen_test_layout_WebPIterator' panicked at 'assertion failed: `(left == right)`
  left: `64`,
 right: `80`: Size of: WebPIterator', src/ffi.rs:2798:5
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.67.1/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.67.1/library/core/src/panicking.rs:64:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /usr/src/rustc-1.67.1/library/core/src/panicking.rs:199:5
   4: libwebp_sys::ffi::bindgen_test_layout_WebPIterator
             at /usr/share/cargo/registry/libwebp-sys-0.9.2/src/ffi.rs:2798:5
   5: libwebp_sys::ffi::bindgen_test_layout_WebPIterator::{{closure}}
             at /usr/share/cargo/registry/libwebp-sys-0.9.2/src/ffi.rs:2795:39
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.67.1/library/core/src/ops/function.rs:507:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.67.1/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- ffi::bindgen_test_layout_WebPMemoryWriter stdout ----
thread 'ffi::bindgen_test_layout_WebPMemoryWriter' panicked at 'assertion failed: `(left == right)`
  left: `16`,
 right: `32`: Size of: WebPMemoryWriter', src/ffi.rs:714:5
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.67.1/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.67.1/library/core/src/panicking.rs:64:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /usr/src/rustc-1.67.1/library/core/src/panicking.rs:199:5
   4: libwebp_sys::ffi::bindgen_test_layout_WebPMemoryWriter
             at /usr/share/cargo/registry/libwebp-sys-0.9.2/src/ffi.rs:714:5
   5: libwebp_sys::ffi::bindgen_test_layout_WebPMemoryWriter::{{closure}}
             at /usr/share/cargo/registry/libwebp-sys-0.9.2/src/ffi.rs:711:43
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.67.1/library/core/src/ops/function.rs:507:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.67.1/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- ffi::bindgen_test_layout_WebPMuxFrameInfo stdout ----
thread 'ffi::bindgen_test_layout_WebPMuxFrameInfo' panicked at 'assertion failed: `(left == right)`
  left: `36`,
 right: `48`: Size of: WebPMuxFrameInfo', src/ffi.rs:2405:5
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.67.1/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.67.1/library/core/src/panicking.rs:64:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /usr/src/rustc-1.67.1/library/core/src/panicking.rs:199:5
   4: libwebp_sys::ffi::bindgen_test_layout_WebPMuxFrameInfo
             at /usr/share/cargo/registry/libwebp-sys-0.9.2/src/ffi.rs:2405:5
   5: libwebp_sys::ffi::bindgen_test_layout_WebPMuxFrameInfo::{{closure}}
             at /usr/share/cargo/registry/libwebp-sys-0.9.2/src/ffi.rs:2402:43
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.67.1/library/core/src/ops/function.rs:507:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.67.1/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- ffi::bindgen_test_layout_WebPYUVABuffer stdout ----
thread 'ffi::bindgen_test_layout_WebPYUVABuffer' panicked at 'assertion failed: `(left == right)`
  left: `48`,
 right: `80`: Size of: WebPYUVABuffer', src/ffi.rs:1517:5
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.67.1/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.67.1/library/core/src/panicking.rs:64:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /usr/src/rustc-1.67.1/library/core/src/panicking.rs:199:5
   4: libwebp_sys::ffi::bindgen_test_layout_WebPYUVABuffer
             at /usr/share/cargo/registry/libwebp-sys-0.9.2/src/ffi.rs:1517:5
   5: libwebp_sys::ffi::bindgen_test_layout_WebPYUVABuffer::{{closure}}
             at /usr/share/cargo/registry/libwebp-sys-0.9.2/src/ffi.rs:1514:41
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.67.1/library/core/src/ops/function.rs:507:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.67.1/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- ffi::bindgen_test_layout_WebPRGBABuffer stdout ----
thread 'ffi::bindgen_test_layout_WebPRGBABuffer' panicked at 'assertion failed: `(left == right)`
  left: `12`,
 right: `24`: Size of: WebPRGBABuffer', src/ffi.rs:1456:5
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.67.1/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.67.1/library/core/src/panicking.rs:64:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /usr/src/rustc-1.67.1/library/core/src/panicking.rs:199:5
   4: libwebp_sys::ffi::bindgen_test_layout_WebPRGBABuffer
             at /usr/share/cargo/registry/libwebp-sys-0.9.2/src/ffi.rs:1456:5
   5: libwebp_sys::ffi::bindgen_test_layout_WebPRGBABuffer::{{closure}}
             at /usr/share/cargo/registry/libwebp-sys-0.9.2/src/ffi.rs:1453:41
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.67.1/library/core/src/ops/function.rs:507:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.67.1/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- ffi::bindgen_test_layout_WebPPicture stdout ----
thread 'ffi::bindgen_test_layout_WebPPicture' panicked at 'assertion failed: `(left == right)`
  left: `172`,
 right: `256`: Size of: WebPPicture', src/ffi.rs:848:5
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.67.1/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.67.1/library/core/src/panicking.rs:64:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /usr/src/rustc-1.67.1/library/core/src/panicking.rs:199:5
   4: libwebp_sys::ffi::bindgen_test_layout_WebPPicture
             at /usr/share/cargo/registry/libwebp-sys-0.9.2/src/ffi.rs:848:5
   5: libwebp_sys::ffi::bindgen_test_layout_WebPPicture::{{closure}}
             at /usr/share/cargo/registry/libwebp-sys-0.9.2/src/ffi.rs:845:38
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.67.1/library/core/src/ops/function.rs:507:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.67.1/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    ffi::bindgen_test_layout_WebPChunkIterator
    ffi::bindgen_test_layout_WebPData
    ffi::bindgen_test_layout_WebPDecBuffer
    ffi::bindgen_test_layout_WebPDecBuffer__bindgen_ty_1
    ffi::bindgen_test_layout_WebPDecoderConfig
    ffi::bindgen_test_layout_WebPIterator
    ffi::bindgen_test_layout_WebPMemoryWriter
    ffi::bindgen_test_layout_WebPMuxFrameInfo
    ffi::bindgen_test_layout_WebPPicture
    ffi::bindgen_test_layout_WebPRGBABuffer
    ffi::bindgen_test_layout_WebPYUVABuffer

test result: FAILED. 8 passed; 11 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.03s


```

**Comment by NoXF** [comment]
thx for the report, It seems the test only covers 64-bit. I don't have a 32-bit env at hand, Do you mind committing some condition compilation code to fix this test case?

**Comment by werdahias** [comment]
```diff

Description: Skip failing bindgen tests on 32-bit arches 
Author: Matthias Geiger <werdahias@riseup.net>
Forwarded: https://github.com/NoXF/libwebp-sys/issues/22 
Last-Update: 2023-09-10
---
This patch header follows DEP-3: http://dep.debian.net/deps/dep3/

--- a/src/ffi.rs
+++ b/src/ffi.rs
@@ -708,6 +708,7 @@ pub struct WebPMemoryWriter {
     pub pad: [u32; 1usize],
 }
 #[test]
+#[cfg(not(target_pointer_width = "32"))]
 fn bindgen_test_layout_WebPMemoryWriter() {
     const UNINIT: ::core::mem::MaybeUninit<WebPMemoryWriter> = ::core::mem::MaybeUninit::uninit();
     let ptr = UNINIT.as_ptr();
@@ -842,6 +843,7 @@ pub struct WebPPicture {
     pub pad7: [*mut ::core::ffi::c_void; 2usize],
 }
 #[test]
+#[cfg(not(target_pointer_width = "32"))]
 fn bindgen_test_layout_WebPPicture() {
     const UNINIT: ::core::mem::MaybeUninit<WebPPicture> = ::core::mem::MaybeUninit::uninit();
     let ptr = UNINIT.as_ptr();
@@ -1450,6 +1452,7 @@ pub struct WebPRGBABuffer {
     pub size: usize,
 }
 #[test]
+#[cfg(not(target_pointer_width = "32"))]
 fn bindgen_test_layout_WebPRGBABuffer() {
     const UNINIT: ::core::mem::MaybeUninit<WebPRGBABuffer> = ::core::mem::MaybeUninit::uninit();
     let ptr = UNINIT.as_ptr();
@@ -1511,6 +1514,7 @@ pub struct WebPYUVABuffer {
     pub a_size: usize,
 }
 #[test]
+#[cfg(not(target_pointer_width = "32"))]
 fn bindgen_test_layout_WebPYUVABuffer() {
     const UNINIT: ::core::mem::MaybeUninit<WebPYUVABuffer> = ::core::mem::MaybeUninit::uninit();
     let ptr = UNINIT.as_ptr();
@@ -1663,6 +1667,7 @@ pub union WebPDecBuffer__bindgen_ty_1 {
     pub YUVA: WebPYUVABuffer,
 }
 #[test]
+#[cfg(not(target_pointer_width = "32"))]
 fn bindgen_test_layout_WebPDecBuffer__bindgen_ty_1() {
     const UNINIT: ::core::mem::MaybeUninit<WebPDecBuffer__bindgen_ty_1> =
         ::core::mem::MaybeUninit::uninit();
@@ -1704,6 +1709,7 @@ impl ::core::fmt::Debug for WebPDecBuffe
     }
 }
 #[test]
+#[cfg(not(target_pointer_width = "32"))]
 fn bindgen_test_layout_WebPDecBuffer() {
     const UNINIT: ::core::mem::MaybeUninit<WebPDecBuffer> = ::core::mem::MaybeUninit::uninit();
     let ptr = UNINIT.as_ptr();
@@ -2183,6 +2189,7 @@ pub struct WebPDecoderConfig {
     pub options: WebPDecoderOptions,
 }
 #[test]
+#[cfg(not(target_pointer_width = "32"))]
 fn bindgen_test_layout_WebPDecoderConfig() {
     const UNINIT: ::core::mem::MaybeUninit<WebPDecoderConfig> = ::core::mem::MaybeUninit::uninit();
     let ptr = UNINIT.as_ptr();
@@ -2285,6 +2292,7 @@ pub struct WebPData {
     pub size: usize,
 }
 #[test]
+#[cfg(not(target_pointer_width = "32"))]
 fn bindgen_test_layout_WebPData() {
     const UNINIT: ::core::mem::MaybeUninit<WebPData> = ::core::mem::MaybeUninit::uninit();
     let ptr = UNINIT.as_ptr();
@@ -2399,6 +2407,7 @@ pub struct WebPMuxFrameInfo {
     pub pad: [u32; 1usize],
 }
 #[test]
+#[cfg(not(target_pointer_width = "32"))]
 fn bindgen_test_layout_WebPMuxFrameInfo() {
     const UNINIT: ::core::mem::MaybeUninit<WebPMuxFrameInfo> = ::core::mem::MaybeUninit::uninit();
     let ptr = UNINIT.as_ptr();
@@ -2792,6 +2801,7 @@ pub struct WebPIterator {
     pub private_: *mut ::core::ffi::c_void,
 }
 #[test]
+#[cfg(not(target_pointer_width = "32"))]
 fn bindgen_test_layout_WebPIterator() {
     const UNINIT: ::core::mem::MaybeUninit<WebPIterator> = ::core::mem::MaybeUninit::uninit();
     let ptr = UNINIT.as_ptr();
@@ -2972,6 +2982,7 @@ pub struct WebPChunkIterator {
     pub private_: *mut ::core::ffi::c_void,
 }
 #[test]
+#[cfg(not(target_pointer_width = "32"))]
 fn bindgen_test_layout_WebPChunkIterator() {
     const UNINIT: ::core::mem::MaybeUninit<WebPChunkIterator> = ::core::mem::MaybeUninit::uninit();
     let ptr = UNINIT.as_ptr();



```

**Comment by werdahias** [comment]
this just skips the tests and doesn't fix them though.
